"""YAML front-matter for the canonical docs.

Docs carry a short metadata header::

    ---
    summary: One sentence on what this document covers.
    keywords: [dns, resolver, spoke, bind]
    ---

Two things depend on this module, and they pull in opposite directions:

* **Retrieval** wants the metadata. Keyword matching over prose alone cannot
  answer a terse follow-up ("what about windows?") or bridge a vocabulary gap
  between what a user calls a thing and what the doc calls it.
* **The reader** must never see it. Docs are served as raw markdown and
  rendered by a small client-side renderer that turns ``---`` into ``<hr>``, so
  an unstripped header would show up as a horizontal rule followed by the raw
  YAML on every single document.

So parsing and stripping live here, once, rather than being re-implemented (and
inconsistently forgotten) at each call site.

Parsing is deliberately fail-soft: a malformed header is treated as "no
metadata" and the document is still returned intact. Losing a keyword boost
degrades ranking slightly; raising an exception would take the docs offline.
"""

import re

__all__ = ["parse", "strip", "split"]

_FM_RE = re.compile(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)", re.DOTALL)


def _parse_block(block):
    """Parse the inside of a front-matter block into a dict.

    PyYAML is used when importable, but this module must not hard-depend on it:
    these routes load during app startup, and a docs nicety is not worth an
    import-time failure. The fallback understands the only two shapes we emit --
    ``key: scalar`` and ``key: [a, b, c]`` -- which is enough, because this
    metadata is generated by tooling in a fixed format rather than hand-authored
    in arbitrary YAML.
    """
    try:
        import yaml  # noqa: PLC0415 - optional, resolved at call time
        data = yaml.safe_load(block)
        return data if isinstance(data, dict) else {}
    except ImportError:
        pass
    except Exception:
        return {}

    out = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if not key:
            continue
        if val.startswith("[") and val.endswith("]"):
            out[key] = [v.strip().strip("'\"") for v in val[1:-1].split(",") if v.strip()]
        else:
            out[key] = val.strip("'\"")
    return out


def split(text):
    """Return ``(metadata, body)``.

    ``body`` is always safe to render. When there is no front-matter the text is
    returned unchanged with empty metadata, so callers never need to branch.
    """
    if not text:
        return {}, text or ""
    # lstrip only leading blank lines: a header is only a header at the very
    # top, and treating a mid-document '---' rule as one would silently eat
    # content.
    lead = len(text) - len(text.lstrip("\r\n"))
    m = _FM_RE.match(text[lead:])
    if not m:
        return {}, text
    meta = _parse_block(m.group(1))
    if not isinstance(meta, dict):
        return {}, text
    return meta, text[lead + m.end():]


def parse(text):
    """The metadata dict only (empty when absent or malformed)."""
    return split(text)[0]


def strip(text):
    """The renderable body only, with any front-matter removed."""
    return split(text)[1]


def keywords_of(meta):
    """Normalised keyword list from parsed metadata.

    Accepts both the list form and a comma-separated string, because hand-edited
    docs drift toward the latter and silently losing those keywords would be
    worse than accepting both.
    """
    kw = meta.get("keywords") or []
    if isinstance(kw, str):
        kw = [k.strip() for k in kw.split(",")]
    return [str(k).strip().lower() for k in kw if str(k).strip()]
